# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import api_logger_pb2 as api__logger__pb2


class ApiLoggerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.sendSingleLog = channel.unary_unary(
                '/apilogger.ApiLogger/sendSingleLog',
                request_serializer=api__logger__pb2.SingleLog.SerializeToString,
                response_deserializer=api__logger__pb2.Empty.FromString,
                )
        self.sendBatchLog = channel.unary_unary(
                '/apilogger.ApiLogger/sendBatchLog',
                request_serializer=api__logger__pb2.BatchLog.SerializeToString,
                response_deserializer=api__logger__pb2.Empty.FromString,
                )


class ApiLoggerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def sendSingleLog(self, request, context):
        """send logs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def sendBatchLog(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ApiLoggerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'sendSingleLog': grpc.unary_unary_rpc_method_handler(
                    servicer.sendSingleLog,
                    request_deserializer=api__logger__pb2.SingleLog.FromString,
                    response_serializer=api__logger__pb2.Empty.SerializeToString,
            ),
            'sendBatchLog': grpc.unary_unary_rpc_method_handler(
                    servicer.sendBatchLog,
                    request_deserializer=api__logger__pb2.BatchLog.FromString,
                    response_serializer=api__logger__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'apilogger.ApiLogger', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ApiLogger(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def sendSingleLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/apilogger.ApiLogger/sendSingleLog',
            api__logger__pb2.SingleLog.SerializeToString,
            api__logger__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def sendBatchLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/apilogger.ApiLogger/sendBatchLog',
            api__logger__pb2.BatchLog.SerializeToString,
            api__logger__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
