{
  "formatVersion": "1.1",
  "component": {
    "group": "src",
    "module": "apilogger-maven",
    "version": "0.0.1-maven",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 19,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "apilogger-maven-0.0.1-maven.jar",
          "url": "apilogger-maven-0.0.1-maven.jar",
          "size": 33810,
          "sha512": "c26393007940646872fce11a77ffef15aa4c74f150cbac99f4c20a7f2bae8aa3bef4c8b7006661f9076de62427aced31cd9b2b631ca6f146f28605ed29fecb4e",
          "sha256": "0e73bfeb35afc8d762f41a51764d2bd9c06aa7cd6cbfeb33fb574ec4a2b82cc8",
          "sha1": "85cbfc8770b0720cf748b72b755ed4545382efe6",
          "md5": "79c645eb6aca84261625239a046a1992"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 19,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "32.1.1-jre"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-protobuf",
          "version": {
            "requires": "1.59.0"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-stub",
          "version": {
            "requires": "1.59.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-netty-shaded",
          "version": {
            "requires": "1.59.0"
          }
        }
      ],
      "files": [
        {
          "name": "apilogger-maven-0.0.1-maven.jar",
          "url": "apilogger-maven-0.0.1-maven.jar",
          "size": 33810,
          "sha512": "c26393007940646872fce11a77ffef15aa4c74f150cbac99f4c20a7f2bae8aa3bef4c8b7006661f9076de62427aced31cd9b2b631ca6f146f28605ed29fecb4e",
          "sha256": "0e73bfeb35afc8d762f41a51764d2bd9c06aa7cd6cbfeb33fb574ec4a2b82cc8",
          "sha1": "85cbfc8770b0720cf748b72b755ed4545382efe6",
          "md5": "79c645eb6aca84261625239a046a1992"
        }
      ]
    }
  ]
}
